config/routes.rb
SpringPetclinic::Application.routes.draw do
  resources :vets

  get 'owners/:owner_id/pets/:id/visits.:format' => 'visits#index'

  resources :owners do
    collection do
      get :search
    end

    resources :pets do
      resources :visits
    end
  end

  root :to => "welcome#index"

end

app/models/owner.rb
java_import org.springframework.samples.petclinic.Owner

class Owner
  extend ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include Spring

  validates_presence_of :first_name, :last_name, :address, :city, :telephone
  validates_format_of :telephone, :with => /[-0-9.+ ]+/, :message => "can only have numbers, punctuation, or spaces"

  def self.find_by_name(name)
    clinic.findOwners(name)
  end

  def self.load(id)
    clinic.loadOwner(id.to_i)
  end

  def save
    clinic.storeOwner(self)
  end
end

app/models/pet.rb
java_import org.springframework.samples.petclinic.Pet

class Pet
  extend ActiveModel::Naming
  include ActiveModel::Validations
  include ActiveModel::Conversion
  include Spring

  Owner; Visit ; PetType # dev-mode: ensure child models are decorated

  def birth_date
    getBirthDate && getBirthDate.to_date
  end

  def birth_date=(date)
    setBirthDate java.util.Date.from_date(date)
  end

  def type=(t)
    setType PetType === t ? t : PetType.load(t.to_i)
  end

  def self.load(id)
    clinic.loadPet(id.to_i)
  end

  def save
    clinic.storePet(self)
  end

  def destroy
    clinic.deletePet(id)
  end
end

app/models/pet_type.rb
java_import org.springframework.samples.petclinic.PetType

class PetType
  extend ActiveModel::Naming
  include ActiveModel::Validations
  include ActiveModel::Conversion
  include Spring

  def self.load(id)
    clinic.getPetTypes.detect {|pt| pt.id == id.to_i }
  end
end

app/models/vet.rb
java_import org.springframework.samples.petclinic.Vet

class Vet
  include ActiveModel::Serializers::Xml
  include ActiveModel::Serializers::JSON
  include Spring

  def serializable_hash(*)
    {
      "id" => id,
      "first_name" => first_name, "last_name" => last_name,
      "specialties" => specialties.map{|s| s.name}.join(', '),
      "nr_of_specialties" => nr_of_specialties
    }
  end
  alias attributes serializable_hash

  def self.all
    clinic.getVets
  end
end

app/models/visit.rb
java_import org.springframework.samples.petclinic.Visit

class Visit
  extend ActiveModel::Naming
  include ActiveModel::Validations
  include ActiveModel::Conversion
  include Spring

  def date
    getDate.to_date
  end

  def date=(date)
    setDate java.util.Date.from_date(date)
  end

  def save
    clinic.storeVisit(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  require 'java_ext'
  require 'spring_helpers'
  include Spring
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  before_filter :load_owner, :only => [:edit, :show, :update]

  def index
    name = params[:lastName] || ''
    @owners = Owner.find_by_name(name)
    if @owners.size < 1
      flash[:notice] = "#{params[:lastName]} #{t(:notFound)}"
      render "search"
    elsif @owners.size == 1
      redirect_to owner_path(@owners.first)
    end
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new
    create_or_update("new")
  end

  def update
    create_or_update("edit")
  end

  private
  def load_owner
    unless (@owner ||= Owner.load params[:id])
      flash[:notice] = t(:notFound)
      redirect_to owners_path
    end
  end

  def create_or_update(template)
    @owner.update_attributes params[:owner]
    if @owner.valid?
      @owner.save
      redirect_to owner_path(@owner)
    else
      render template
    end
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_filter :load_owner
  before_filter :new_pet, :only => [:new, :create]
  before_filter :load_pet, :only => [:show, :edit, :update, :destroy]

  def new
    @types = clinic.pet_types
  end

  def show
  end

  def edit
    @types = clinic.pet_types
  end

  def create
    create_or_update('new')
  end

  def update
    create_or_update('edit')
  end

  def destroy
    @pet.destroy
    redirect_to owner_path(params[:owner_id])
  end

  private
  def load_owner
    unless (@owner ||= Owner.load params[:owner_id].to_i)
      flash[:notice] = t(:notFound)
      redirect_to owners_path
    end
  end

  def load_pet
    @pet = Pet.load(params[:id])
  end

  def new_pet
    @pet = Pet.new.tap {|pet| pet.owner = @owner }
  end

  def create_or_update(template)
    @pet.update_attributes params[:pet]
    if @pet.valid?
      @pet.save
      redirect_to owner_path(@owner)
    else
      render template
    end
  end
end

app/controllers/vets_controller.rb
class VetsController < ApplicationController
  def index
    @vets = Vet.all
    respond_to do |format|
      format.html
      format.xml do
        render :xml => @vets.to_a.to_xml
      end
      format.json do
        render :json => @vets.to_a.to_json
      end
    end
  end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_filter :load_pet
  before_filter :new_visit, :only => [:new, :create]
  before_filter :load_visit, :only => [:show, :edit, :update]

  def index
    @visits = @pet.visits
    respond_to do |format|
      format.atom
    end
  end

  def new
  end

  def edit
  end

  def create
    create_or_update('new')
  end

  def update
    create_or_update('edit')
  end

  private
  def load_pet
    @pet = Pet.load(params[:pet_id])
  end

  def new_visit
    @visit = Visit.new.tap {|v| v.pet = @pet }
  end

  def load_visit
    unless (@visit = @pet.visits.detect {|v| v.id == params[:id].to_i})
      flash[:notice] = t(:notFound)
      redirect_to owner_path(@pet.owner)
    end
  end

  def create_or_update(template)
    @visit.update_attributes params[:visit]
    if @visit.valid?
      @visit.save
      redirect_to owner_path(@pet.owner)
    else
      render template
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/views/layouts/application.html.erb
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <%= stylesheet_link_tag :all %>
  <title>PetClinic :: a Rails + Spring demonstration</title>	
</head>

<body>

  <div id="main">

  <%= yield %>

  <table class="footer">
    <tr>
      <td><a href="/">Home</a></td>
      <td align="right"><%= image_tag 'springsource-logo.png', :alt => "Sponsored by SpringSource" %></td>
    </tr>
  </table>

  </div>
</body>

</html>

app/views/owners/_form.html.erb
<%= form_for @owner do |f| %>
  <%= render :partial => 'shared/errors', :locals => { :object => @owner } %>
  <table>
    <tr>
      <th>
        <%= f.label :first_name %>
        <br/>
        <%= f.text_field :first_name, :size => 30, :maxlength => 80 %>
      </th>
    </tr>
    <tr>
      <th>
        <%= f.label :last_name %>
        <br/>
        <%= f.text_field :last_name, :size => 30, :maxlength => 80 %>
      </th>
    </tr>
    <tr>
      <th>
        <%= f.label :address %>
        <br/>
        <%= f.text_field :address, :size => 30, :maxlength => 80 %>
      </th>
    </tr>
    <tr>
      <th>
        <%= f.label :city %>
        <br/>
        <%= f.text_field :city, :size => 30, :maxlength => 80 %>
      </th>
    </tr>
    <tr>
      <th>
        <%= f.label :telephone %>
        <br/>
        <%= f.text_field :telephone, :size => 20, :maxlength => 20 %>
      </th>
    </tr>
    <tr>
      <td>
        <p class="submit"><%= f.submit "#{@owner.new? ? 'Add' : 'Update'} Owner" %></p>
      </td>
    </tr>
  </table>
<% end -%>

app/views/owners/edit.html.erb
<h2>Owner:</h2>

<%= render :partial => 'form' %>

app/views/owners/index.html.erb
<h2>Owners:</h2>

<table>
  <thead>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>Telephone</th>
    <th>Pets</th>
  </thead>
  <% @owners.each do |owner| -%>
    <tr>
      <td>
          <%= link_to "#{owner.firstName} #{owner.lastName}", owner_path(owner.id) %>
      </td>
      <td><%= owner.address %></td>
      <td><%= owner.city %></td>
      <td><%= owner.telephone %></td>
      <td><% owner.pets.each do |pet| -%><%= pet.name %>&nbsp;<% end -%></td>
    </tr>
  <% end -%>
</table>
<br/>
<%= link_to 'Add Owner', new_owner_path %>

app/views/owners/new.html.erb
<h2>New Owner:</h2>

<%= render :partial => 'form' %>

app/views/owners/show.html.erb
<h2>Owner Information</h2>

<table>
  <tr>
    <th>Name</th>
    <td><b><%= @owner.first_name %> <%= @owner.last_name %></b></td>
  </tr>
  <tr>
    <th>Address</th>
    <td><%= @owner.address %></td>
  </tr>
  <tr>
    <th>City</th>
    <td><%= @owner.city %></td>
  </tr>
  <tr>
    <th>Telephone </th>
    <td><%= @owner.telephone %></td>
  </tr>
</table>
<table class="table-buttons">
  <tr>
    <td>
      <%= link_to 'Edit Owner', edit_owner_path %>
    </td>
    <td>
      <%= link_to 'Destroy Owner', owner_path(@owner), :confirm => 'Are you sure?', :method => :delete %>
    </td>
    <td>
      <%= link_to 'Add New Pet', new_owner_pet_path(@owner) %>
    </td>
  </tr>
</table>

<h2>Pets and Visits</h2>

<% @owner.pets.each do |pet| -%>
  <table width="94%">
    <tr>
      <td valign="top">
        <table>
          <tr>
            <th>Name</th>
            <td><b><%= pet.name %></b></td>
          </tr>
          <tr>
            <th>Birth Date</th>
            <td><%= pet.birth_date.to_s %></td>
          </tr>
          <tr>
            <th>Type</th>
            <td><%= pet.type.name %></td>
          </tr>
        </table>
      </td>
      <td valign="top">
        <table>
          <thead>
            <th>Visit Date</th>
            <th>Description</th>
          </thead>
          <% pet.visits.each do |visit| -%>
            <tr>
              <td><%= visit.date.to_s %></td>
              <td><%= visit.description %></td>
            </tr>
          <% end -%>
        </table>
      </td>
    </tr>
  </table>
  <table class="table-buttons">
    <tr>
      <td>
        <%= link_to 'Edit Pet', edit_owner_pet_path(@owner, pet) %>
      </td>
      <td></td>
      <td>
        <%= link_to 'Add Visit', new_owner_pet_visit_path(@owner, pet) %>
      </td>
      <td></td>
      <td>
        <%= link_to 'Atom Feed', owner_pet_visits_path(@owner, pet, 'atom') %>
      </td>
    </tr>
  </table>
<% end -%>

app/views/pets/_form.html.erb
<b>Owner:</b> <%= @pet.owner.first_name %> <%= @pet.owner.last_name %>
<br/>
<%= form_for [@owner, @pet] do |f| %>
  <%= render :partial => 'shared/errors', :locals => { :object => @pet } %>
  <table>
    <tr>
      <th>
        <%= f.label :name %>
        <br/>
        <%= f.text_field :name, :size => 30, :maxlength => 30 %>
      </th>
    </tr>
    <tr>
      <th>
        <%= f.label :birth_date %>
        <br/>
        <%= f.date_select :birth_date %>
      </th>
    </tr>
    <tr>
      <th>
        <%= f.label :type %>
        <br/>
        <%= f.select :type, options_from_collection_for_select(@types, "id", "name", @pet.type && @pet.type.id) %>
      </th>
    </tr>
    <tr>
      <td>
        <p class="submit"><%= f.submit "#{@pet.new? ? 'Add' : 'Update'} Pet" %></p>
      </td>
    </tr>
  </table>
<% end -%>

app/views/pets/edit.html.erb
<h2>Pet</h2>

<%= render :partial => "form" %>

<%= form_for [@owner, @pet], :html => {:method => 'delete'} do |f| %>
  <p class="submit"><%= f.submit "Delete Pet", :confirm => "Are you sure?" %></p>
<% end -%>

<b>Visits:</b>
<table width="333">
  <tr>
    <th>Date</th>
    <th>Description</th>
  </tr>
  <% @pet.visits.each do |visit| -%>
    <% unless visit.new? -%>
      <tr>
        <td><%= link_to visit.date.to_s, edit_owner_pet_visit_path(@owner, @pet, visit) %></td>
        <td><%= visit.description %></td>
      </tr>
    <% end -%>
  <% end -%>
</table>

app/views/pets/new.html.erb
<h2>New Pet</h2>

<%= render :partial => 'form' %>

app/views/shared/_errors.html.erb
<% unless object.errors.empty? -%>
<div class="errors">
  <p>There were problems with your entry, please correct them and re-submit.</p>
  <ul>
    <% object.errors.full_messages.each do |e| -%>
    <li><%= e %></li>
    <% end -%>
  </ul>
</div>
<% end -%>

app/views/vets/index.html.erb
<h2>Veterinarians:</h2>

<table>
  <thead>
    <th>Name</th>
    <th>Specialties</th>
  </thead>
  <% @vets.each do |vet| -%>
    <tr>
      <td><%= vet.firstName %> <%= vet.lastName %></td>
      <td>
        <% vet.specialties.each do |specialty| -%>
          <%= specialty.name %>
        <% end -%>
        <% if vet.nr_of_specialties == 0 %>none<% end -%>
      </td>
    </tr>
  <% end -%>
</table>
<table class="table-buttons">
  <tr>
    <td>
      <a href="/vets.xml">View as XML</a>
    </td>
    <td>
      <a href="/vets.json">View as JSON</a>
    </td>
  </tr>
</table>

app/views/visits/_form.html.erb
<%= form_for [@pet.owner, @pet, @visit] do |f| %>
  <b>Pet:</b>
  <table width="333">
    <thead>
      <th>Name</th>
      <th>Birth Date</th>
      <th>Type</th>
      <th>Owner</th>
    </thead>
    <tr>
      <td><%= @pet.name %></td>
      <td><%= @pet.birth_date.to_s %></td>
      <td><%= @pet.type.name %></td>
      <td><%= @pet.owner.firstName %> <%= @pet.owner.lastName %></td>
    </tr>
  </table>

  <table width="333">
    <tr>
      <th>
        <%= f.label :date %>
        <br/>
      </th>
      <td>
        <%= f.date_select :date %>
      </td>
    <tr/>
    <tr>
      <th valign="top">
        <%= f.label :description %>
        <br/>
      </th>
      <td>
        <%= f.text_area :description, :rows => 10, :cols => 25 %>
      </td>
    </tr>
    <tr>
      <td colspan="2">
        <p class="submit"><%= f.submit "#{@visit.new? ? 'Add' : 'Update'} Visit" %></p>
      </td>
    </tr>
  </table>
<% end -%>

<br/>
<b>Previous Visits:</b>
<table width="333">
  <tr>
    <th>Date</th>
    <th>Description</th>
  </tr>
  <% @pet.visits.each do |visit| -%>
    <% unless visit.new? -%>
      <tr>
        <td><%= visit.date.to_s %></td>
        <td><%= visit.description %></td>
      </tr>
    <% end -%>
  <% end -%>
</table>

app/views/visits/edit.html.erb
<h2>Visit:</h2>

<%= render :partial => "form" %>

app/views/visits/new.html.erb
<h2>New Visit:</h2>

<%= render :partial => "form" %>

app/views/welcome/index.html.erb
<%= image_tag 'pets.png', :align => "right", :style => "position:relative;right:30px;" %>
<h2><%= t :welcome %></h2>

<ul>
  <li><a href="/owners/search">Find owner</a></li>
  <li><a href="/vets">Display all veterinarians</a></li>
  <li><a href="/html/tutorial.html">Tutorial</a></li>
</ul>

<p>&nbsp;</p>
<p>&nbsp;</p>