src/main/webapp/WEB-INF/config/routes.rb
SpringPetclinic::Application.routes.draw do
  resources :vets

  get 'owners/:owner_id/pets/:id/visits.:format' => 'visits#index'

  get 'owners/search' => 'owners#search'

  root :to => "welcome#index"

end

src/main/webapp/WEB-INF/app/models/vet.rb
module VetMethods
  module ClassMethods
    def all
      clinic.getVets
    end

    def model_name
      ActiveSupport::ModelName.new("vet")
    end

    def find(id)
      session_factory.with_session { |s| s.load(Vet, id.to_i.to_java(:int)) }
    end
  end

  module InstanceMethods
    def initialize(*args)
      super()
      assign_attributes(args.extract_options!)
    end

    def to_param
      get_id.to_s
    end

    def new_record?
      isNew
    end

    def errors
      []
    end

    def save
      session_factory.transaction do |session|
        if get_id.nil?
          session.save(self)
        else
          session.merge(self)
        end
      end
    end

    def update_attributes(hash)
      assign_attributes(hash)
      session_factory.transaction do |session|
        session.merge(self)
      end
    end

    def destroy
      session_factory.transaction do |session|
        session.delete(self)
      end
    end

    private
    def assign_attributes(hash)
      hash.each do |k,v|
        send("#{k}=", v)
      end
    end
  end
end

class org::springframework::samples::petclinic::Vet
  include Spring
  include VetMethods::InstanceMethods
  extend VetMethods::ClassMethods
end

Vet = org::springframework::samples::petclinic::Vet

src/main/webapp/WEB-INF/app/controllers/owners_controller.rb
class OwnersController < ApplicationController
end

src/main/webapp/WEB-INF/app/controllers/sample_controller.rb
class SampleController < ApplicationController
  def index
    render :text => "Hello from #{self.class.name}"
  end

  def routes
    render :text => ActionController::Routing::Routes.routes.to_s
  end
end

src/main/webapp/WEB-INF/app/controllers/vets_controller.rb
class VetsController < ApplicationController
  def index
    @vets = clinic.vets
    respond_to do |format|
      format.xml
      format.json do
        vets_hash = @vets.map do |vet|
          { "id" => vet.id,
            "firstName" => vet.firstName,
            "lastName" => vet.lastName
          }.tap do |h|
            unless vet.specialties.empty?
              h["specialties"] = vet.specialties.map {|s| { "id" => s.id, "name" => s.name } }
            end
          end
        end
        render :json => vets_hash
      end
    end
  end
end

src/main/webapp/WEB-INF/app/helpers/vets_helper.rb
module VetsHelper
end

src/main/webapp/WEB-INF/app/views/layouts/vets.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
       "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <title>Vets: <%= controller.action_name %></title>
  <%= stylesheet_link_tag 'scaffold' %>
</head>
<body>

<p style="color: green"><%= flash[:notice] %></p>

<%= yield %>

</body>
</html>

src/main/webapp/WEB-INF/app/views/owners/search.html.erb
<h2>Find Owners:</h2>

<% form_tag '/owners', :method => :get do -%>
  <table>
    <tr>
      <th>
        <label for="lastName">Last name:</label>
        <br/> 
        <%= search_field_tag "lastName", params[:lastName], :size => 30, :maxlength => 80 %>
      </th>
    </tr>
    <tr>
      <td><p class="submit"><input type="submit" value="Find Owners"/></p></td>
    </tr>
  </table>
<% end -%>

<br/>
<%= link_to 'Add Owner', '/owners/new' %>

src/main/webapp/WEB-INF/app/views/vets/edit.html.erb
<h1>Editing vet</h1>

<% form_for(@vet) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', @vet %> |
<%= link_to 'Back', vets_path %>

src/main/webapp/WEB-INF/app/views/vets/new.html.erb
<h1>New vet</h1>

<% form_for(@vet) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', vets_path %>

src/main/webapp/WEB-INF/app/views/vets/show.html.erb
<p>
  <b>First name:</b>
  <%=h @vet.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%=h @vet.last_name %>
</p>


<%= link_to 'Edit', edit_vet_path(@vet) %> |
<%= link_to 'Back', vets_path %>